### ISSUE TITLE
Banner Bottoms

### ISSUE THREAD

**Issue by conneroisu** [conneroisu/conneroh.com#148]
Should use the following css for styling of items that preview banneras:
```css
.box {
  mask: radial-gradient(30px at top,#0000 calc(100% - 1px),#000) 50%/55.5px 100%
}
```
